//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : AppClass.sm
//

#ifndef APPCLASS_SM_H
#define APPCLASS_SM_H


#define SMC_USES_IOSTREAMS

#include <statemap.h>

// Forward declarations.
class Map1;
class Map1_Start;
class Map1_Name;
class Map1_Zone;
class Map1_OK;
class Map1_Error;
class Map1_Default;
class AppClassState;
class AppClassContext;
class AppClass;

class AppClassState :
    public statemap::State
{
public:

    AppClassState(const char * const name, const int stateId)
    : statemap::State(name, stateId)
    {};

    virtual void Entry(AppClassContext&) {};
    virtual void Exit(AppClassContext&) {};

    virtual void Dot(AppClassContext& context);
    virtual void EOS(AppClassContext& context);
    virtual void Error(AppClassContext& context);
    virtual void Reset(AppClassContext& context);
    virtual void Symbol(AppClassContext& context, char sym);
    virtual void Unknown(AppClassContext& context);

protected:

    virtual void Default(AppClassContext& context);
};

class Map1
{
public:

    static Map1_Start Start;
    static Map1_Name Name;
    static Map1_Zone Zone;
    static Map1_OK OK;
    static Map1_Error Error;
};

class Map1_Default :
    public AppClassState
{
public:

    Map1_Default(const char * const name, const int stateId)
    : AppClassState(name, stateId)
    {};

    virtual void Unknown(AppClassContext& context);
    virtual void Reset(AppClassContext& context);
};

class Map1_Start :
    public Map1_Default
{
public:
    Map1_Start(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Entry(AppClassContext&);
    virtual void Error(AppClassContext& context);
    virtual void Symbol(AppClassContext& context, char sym);
};

class Map1_Name :
    public Map1_Default
{
public:
    Map1_Name(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Dot(AppClassContext& context);
    virtual void Error(AppClassContext& context);
    virtual void Symbol(AppClassContext& context, char sym);
};

class Map1_Zone :
    public Map1_Default
{
public:
    Map1_Zone(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void EOS(AppClassContext& context);
    virtual void Error(AppClassContext& context);
    virtual void Symbol(AppClassContext& context, char sym);
};

class Map1_OK :
    public Map1_Default
{
public:
    Map1_OK(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

};

class Map1_Error :
    public Map1_Default
{
public:
    Map1_Error(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Symbol(AppClassContext& context, char sym);
};

class AppClassContext :
    public statemap::FSMContext
{
public:

    explicit AppClassContext(AppClass& owner)
    : FSMContext(Map1::Start),
      _owner(owner)
    {};

    AppClassContext(AppClass& owner, const statemap::State& state)
    : FSMContext(state),
      _owner(owner)
    {};

    virtual void enterStartState()
    {
        getState().Entry(*this);
        return;
    }

    inline AppClass& getOwner()
    {
        return (_owner);
    };

    inline AppClassState& getState()
    {
        if (_state == NULL)
        {
            throw statemap::StateUndefinedException();
        }

        return dynamic_cast<AppClassState&>(*_state);
    };

    inline void Dot()
    {
        getState().Dot(*this);
    };

    inline void EOS()
    {
        getState().EOS(*this);
    };

    inline void Error()
    {
        getState().Error(*this);
    };

    inline void Reset()
    {
        getState().Reset(*this);
    };

    inline void Symbol(char sym)
    {
        getState().Symbol(*this, sym);
    };

    inline void Unknown()
    {
        getState().Unknown(*this);
    };

private:
    AppClass& _owner;
};


#endif // APPCLASS_SM_H

//
// Local variables:
//  buffer-read-only: t
// End:
//
